-   repo: https://github.com/kintoandar/pre-commit.git
    sha: v2.1.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate

-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: trailing-whitespace
